CREATE TABLE Majors (
    MAJOR_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE Students (
    STUDENT_ID SERIAL PRIMARY KEY,
    PASSWORD VARCHAR(255) NOT NULL,
    GRADE VARCHAR(20),
    MAJOR_ID INT REFERENCES Majors(MAJOR_ID),
    UNITS_TAKEN INT DEFAULT 0
);

CREATE TABLE Courses (
    COURSE_ID SERIAL PRIMARY KEY,
    COURSE_NAME VARCHAR(100) NOT NULL,
    COURSE_UNITS INT NOT NULL,
    MAX_SEATS INT NOT NULL,
    MAX_WAITLIST INT NOT NULL,
    PREREQUISITE_COURSE_ID INT REFERENCES Courses(COURSE_ID)
);

CREATE TABLE Enrollment (
    STUDENT_ID INT REFERENCES Students(STUDENT_ID),
    COURSE_ID INT REFERENCES Courses(COURSE_ID),
    STATUS VARCHAR(20) CHECK (STATUS IN ('ENROLLED', 'WAITLISTED')),
    ENROLL_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (STUDENT_ID, COURSE_ID)
);

CREATE TABLE Major_Requirements (
    MAJOR_ID INT REFERENCES Majors(MAJOR_ID),
    COURSE_ID INT REFERENCES Courses(COURSE_ID),
    PRIMARY KEY (MAJOR_ID, COURSE_ID)
);
